name: Enter/Exit Prerelease

on:
  workflow_dispatch: {}

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ contains(github.ref_name, 'release-v') }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - run: bash scripts/git-user-config.sh
      - name: Set prerelease state
        run: [ -f .changeset/pre.json ] && npx changeset pre exit rc || npx changeset pre enter rc
      - name: Commit state
        run: |
          git add .
          git commit -m "Set prerelease state"
          git push --all origin
      - name: Dispatch Release PR
        uses: ./.github/actions/dispatch-release-pr

