name: Release PR

on:
  push:
    branches:
      - master
      - release-v*
  workflow_dispatch: {}

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Set release title variable
        if: ${{ contains(github.ref_name, 'release-v') }}
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          BRANCH_VERSION=$(npx semver -c $(echo $BRANCH_NAME | sed "s/release-v//g"))
          PACKAGE_JSON_NEXT_PATCH=$(npx semver -i $(node --print --eval "require('./package.json').version"))
          NEXT_VERSION=$(npx semver $BRANCH_VERSION $PACKAGE_JSON_NEXT_PATCH | tail -n 1)
          echo "TITLE=Release v${NEXT_VERSION}" >> $GITHUB_ENV
      - name: Create Release PR
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: ${{ env.TITLE || 'Unreleased' }}
